#!/bin/sh

curl -o fanpaket.zip http://www.ulisses-spiele.de/download/889/
unzip fanpaket.zip
rm fanpaket.zip
mv "Das Schwarze Auge - Fanpaket - 2013.07.29" fanpaket
cd fanpaket
mv Fanware-schmaler-Balken.png "balken-schmal.png"
mv Archetyp\ -\ Alanfanerin.png "archetyp-alanfanerin.png"
mv Balken\ -\ Seite\ -\ rechts.png "balken-rechts.png"
mv Archetyp\ -\ Gjalskerl*nder\ Kundschafterin.png "archetyp-gjalskerlaender-kundschafterin.png"
mv Archetyp\ -\ Kampfmagier.png "archetyp-kampfmagier.png"
mv Archetyp\ -\ Katzenhexe.png "archetyp-katzenhexe.png"
mv Archetyp\ -\ Norbardin.png "archetyp-norbardin.png"
mv Archetyp\ -\ Alchimistin.png "archetyp-alchimistin.png"
mv Kasten\ -\ Viertelseiter.png "kasten-viertelseiter.png"
mv Archetyp\ -\ Draconiterin.png "archetyp-draconiterin.png"
mv Symbol\ -\ Nandus.png "symbol-nandus.png"
mv Archetyp\ -\ Krieger.png "archetyp-krieger.png"
mv Kasten\ -\ Achtelseiter.png "kasten-achtelseiter.png"
mv Archetyp\ -\ Goblin-Rattenf*nger.png "archetyp-goblin-rattenfaenger.png"
mv Archetyp\ -\ Magier.png "archetyp-magierin.png"
mv Archetyp\ -\ Einbrecherin.png "archetyp-einbrecherin.png"
mv Archetyp\ -\ Schwertgesellin.png "archetyp-schwertgesellin.png"
mv Archetyp\ -\ Praiosgeweihte.png "archetyp-praiosgeweihte.png"
mv Logo\ -\ Fanware+.png "logo-fanware.png"
mv Archetyp\ -\ Achazkrieger.png "archetyp-achazkrieger.png"
mv Archetyp\ -\ Waldelf.png "archetyp-waldelf.png"
mv Balken\ -\ Seite\ \(Symbole\)\ -\ rechts.png "balken-symbole-rechts.png"
mv Archetyp\ -\ Auelfe.png "archetyp-auelfe.png"
mv Logo\ -\ Fanprodukt.png "logo-fanprodukt.png"
mv Symbol\ -\ Aves.png "symbol-aves.png"
mv Archetyp\ -\ Piratin.png "archetyp-piratin.png"
mv Archetyp\ -\ Entdecker.png "archetyp-entdecker.png"
mv Balken\ -\ Seite\ \(Symbole\)\ -\ links.png "balken-symbole-links.png"
mv Kasten\ -\ Halbseiter.png "kasten-halbseiter.png"
mv Archetyp\ -\ Rondrageweihter.png "archetyp-rondrageweihter.png"
mv Archetyp\ -\ Angroschgeweihter.png "archetyp-angroschgeweihter.png"
mv Archetyp\ -\ Thorwaler.png "archetyp-thorwaller.png"
mv Archetyp\ -\ Schwarzmagierin.png "archetyp-schwarzmagierin.png"
mv Balken\ -\ Seite\ -\ links.png "balken-links.png"
mv Archetyp\ -\ Kr*tenhexe.png "archetyp-kroetenhexe.png"
mv Balken\ -\ waagerecht\ -\ doppelt.png "balken-doppelt.png"
mv Archetyp\ -\ Ritter.png "archetyp-ritter.png"
mv Logo\ -\ Fanprojekt.png "logo-fanprojekt.png"
mv Logo\ -\ Fanseite.png "logo-fanseite.png"
mv Archetyp\ -\ Kartographin.png "archetyp-kartographin.png"
mv Balken\ -\ waagerecht.png "balken.png"
mv Symbol\ -\ Simia.png "symbol-simia.png"
mv Archetyp\ -\ F*hnrich.png "archetyp-faehnrich.png"
mv Archetyp\ -\ Zwerg.png "archetyp-zwerg.png"
